name: masrofnaa
description: A new personal home app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.01

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  sqflite:
  path:
  intl:
  image_picker:
  shared_preferences:
  path_provider:
  flutter_localizations:
    sdk: flutter
  # easy_localization:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/dollar.png
  #   - images/a_dot_ham.jpeg

  
  fonts:
  # First Font
  #   - family: GE
  #     fonts:
  #       - asset: fonts/GE_SS.otf
  # Second Font
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat.ttf
  # Third Font
    - family: Greta
      fonts:
        - asset: fonts/Greta.ttf
  # Fourth Font
    - family: AJ
      fonts:
        - asset: fonts/alj.ttf
